# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class TronSignedTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 253
    FIELDS = {
        1: ('signature', p.BytesType, 0),
    }

    def __init__(
        self,
        signature: bytes = None,
    ) -> None:
        self.signature = signature
