# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p
from .TronContractMessages import TronContractMessages


class TronParameter(p.MessageType):
    FIELDS = {
        1: ('api', p.UnicodeType, 0),
        2: ('payload', TronContractMessages, 0),
    }

    def __init__(
        self,
        api: str = None,
        payload: TronContractMessages = None,
    ) -> None:
        self.api = api
        self.payload = payload
