# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p
from .TronParameter import TronParameter


class TronContract(p.MessageType):
    FIELDS = {
        1: ('type', p.UVarintType, 0),
        2: ('parameter', TronParameter, 0),
    }

    def __init__(
        self,
        type: int = None,
        parameter: TronParameter = None,
    ) -> None:
        self.type = type
        self.parameter = parameter
