# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class TronUpdateAssetContract(p.MessageType):
    FIELDS = {
        1: ('owner_address', p.BytesType, 0),
        2: ('description', p.BytesType, 0),
        3: ('url', p.BytesType, 0),
        4: ('new_limit', p.UVarintType, 0),
        5: ('new_public_limit', p.UVarintType, 0),
    }

    def __init__(
        self,
        owner_address: bytes = None,
        description: bytes = None,
        url: bytes = None,
        new_limit: int = None,
        new_public_limit: int = None,
    ) -> None:
        self.owner_address = owner_address
        self.description = description
        self.url = url
        self.new_limit = new_limit
        self.new_public_limit = new_public_limit
