# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class TronVoteAssetContract(p.MessageType):
    FIELDS = {
        1: ('owner_address', p.BytesType, 0),
        2: ('vote_address', p.BytesType, p.FLAG_REPEATED),
        3: ('support', p.BoolType, 0),
        5: ('count', p.UVarintType, 0),
    }

    def __init__(
        self,
        owner_address: bytes = None,
        vote_address: List[bytes] = None,
        support: bool = None,
        count: int = None,
    ) -> None:
        self.owner_address = owner_address
        self.vote_address = vote_address if vote_address is not None else []
        self.support = support
        self.count = count
