# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore
from .TronVote import TronVote


class TronVoteWitnessContract(p.MessageType):
    FIELDS = {
        1: ('owner_address', p.BytesType, 0),
        2: ('votes', TronVote, p.FLAG_REPEATED),
        3: ('support', p.BoolType, 0),
    }

    def __init__(
        self,
        owner_address: bytes = None,
        votes: List[TronVote] = None,
        support: bool = None,
    ) -> None:
        self.owner_address = owner_address
        self.votes = votes if votes is not None else []
        self.support = support
