# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore
from .TronFrozenSupply import TronFrozenSupply


class TronAssetIssueContract(p.MessageType):
    FIELDS = {
        1: ('owner_address', p.BytesType, 0),
        2: ('name', p.BytesType, 0),
        3: ('abbr', p.BytesType, 0),
        4: ('total_supply', p.UVarintType, 0),
        5: ('frozen_supply', TronFrozenSupply, p.FLAG_REPEATED),
        6: ('trx_num', p.UVarintType, 0),
        8: ('num', p.UVarintType, 0),
        9: ('start_time', p.UVarintType, 0),
        10: ('end_time', p.UVarintType, 0),
        16: ('vote_score', p.UVarintType, 0),
        20: ('description', p.BytesType, 0),
        21: ('url', p.BytesType, 0),
        22: ('free_asset_net_limit', p.UVarintType, 0),
        23: ('public_free_asset_net_limit', p.UVarintType, 0),
        24: ('public_free_asset_net_usage', p.UVarintType, 0),
        25: ('public_latest_free_net_time', p.UVarintType, 0),
    }

    def __init__(
        self,
        owner_address: bytes = None,
        name: bytes = None,
        abbr: bytes = None,
        total_supply: int = None,
        frozen_supply: List[TronFrozenSupply] = None,
        trx_num: int = None,
        num: int = None,
        start_time: int = None,
        end_time: int = None,
        vote_score: int = None,
        description: bytes = None,
        url: bytes = None,
        free_asset_net_limit: int = None,
        public_free_asset_net_limit: int = None,
        public_free_asset_net_usage: int = None,
        public_latest_free_net_time: int = None,
    ) -> None:
        self.owner_address = owner_address
        self.name = name
        self.abbr = abbr
        self.total_supply = total_supply
        self.frozen_supply = frozen_supply if frozen_supply is not None else []
        self.trx_num = trx_num
        self.num = num
        self.start_time = start_time
        self.end_time = end_time
        self.vote_score = vote_score
        self.description = description
        self.url = url
        self.free_asset_net_limit = free_asset_net_limit
        self.public_free_asset_net_limit = public_free_asset_net_limit
        self.public_free_asset_net_usage = public_free_asset_net_usage
        self.public_latest_free_net_time = public_latest_free_net_time
