# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class TronAccountUpdateContract(p.MessageType):
    FIELDS = {
        1: ('account_name', p.BytesType, 0),
        2: ('owner_address', p.BytesType, 0),
    }

    def __init__(
        self,
        account_name: bytes = None,
        owner_address: bytes = None,
    ) -> None:
        self.account_name = account_name
        self.owner_address = owner_address
