# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class TronFreezeBalanceContract(p.MessageType):
    FIELDS = {
        1: ('owner_address', p.BytesType, 0),
        2: ('frozen_balance', p.UVarintType, 0),
        3: ('frozen_duration', p.UVarintType, 0),
    }

    def __init__(
        self,
        owner_address: bytes = None,
        frozen_balance: int = None,
        frozen_duration: int = None,
    ) -> None:
        self.owner_address = owner_address
        self.frozen_balance = frozen_balance
        self.frozen_duration = frozen_duration
