# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore
from .TronContract import TronContract


class TronTransaction(p.MessageType):
    FIELDS = {
        1: ('ref_block_bytes', p.BytesType, 0),
        4: ('ref_block_hash', p.BytesType, 0),
        8: ('expiration', p.UVarintType, 0),
        11: ('contract', TronContract, p.FLAG_REPEATED),
        14: ('timestamp', p.UVarintType, 0),
    }

    def __init__(
        self,
        ref_block_bytes: bytes = None,
        ref_block_hash: bytes = None,
        expiration: int = None,
        contract: List[TronContract] = None,
        timestamp: int = None,
    ) -> None:
        self.ref_block_bytes = ref_block_bytes
        self.ref_block_hash = ref_block_hash
        self.expiration = expiration
        self.contract = contract if contract is not None else []
        self.timestamp = timestamp
