# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class TronParticipateAssetIssueContract(p.MessageType):
    FIELDS = {
        1: ('owner_address', p.BytesType, 0),
        2: ('to_address', p.BytesType, 0),
        3: ('asset_name', p.BytesType, 0),
        4: ('amount', p.UVarintType, 0),
    }

    def __init__(
        self,
        owner_address: bytes = None,
        to_address: bytes = None,
        asset_name: bytes = None,
        amount: int = None,
    ) -> None:
        self.owner_address = owner_address
        self.to_address = to_address
        self.asset_name = asset_name
        self.amount = amount
